"""Add Payee entity and payee_id to transactions

Revision ID: 190752f928dd
Revises: 75a2fd9fbc89
Create Date: 2026-01-15 14:03:42.882416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190752f928dd'
down_revision: Union[str, None] = '75a2fd9fbc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('payee_type', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payees_autocomplete', 'payees', ['user_id', 'transaction_count', 'last_used_at'], unique=False)
    op.create_index('idx_payees_unique_user_canonical', 'payees', ['user_id', 'canonical_name'], unique=True)
    op.create_index(op.f('ix_payees_id'), 'payees', ['id'], unique=False)
    op.create_index(op.f('ix_payees_user_id'), 'payees', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('payee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'payees', ['payee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_column('transactions', 'payee_id')
    op.drop_index(op.f('ix_payees_user_id'), table_name='payees')
    op.drop_index(op.f('ix_payees_id'), table_name='payees')
    op.drop_index('idx_payees_unique_user_canonical', table_name='payees')
    op.drop_index('idx_payees_autocomplete', table_name='payees')
    op.drop_table('payees')
    # ### end Alembic commands ###
