"""Add institution and account_number fields to accounts table

Revision ID: 3c1957ec05e2
Revises: f77256cf0133
Create Date: 2026-01-25 14:22:26.102698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1957ec05e2'
down_revision: Union[str, None] = 'f77256cf0133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('institution', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('account_number', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_number')
    op.drop_column('accounts', 'institution')
    # ### end Alembic commands ###
