"""add is_starred column to transactions

Revision ID: 5c227d63663a
Revises: c1792f7aa7ce
Create Date: 2026-01-24 16:48:23.521963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c227d63663a'
down_revision: Union[str, None] = 'c1792f7aa7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payee_patterns_payee', table_name='payee_matching_patterns')
    op.drop_index('idx_payee_patterns_user', table_name='payee_matching_patterns')
    op.create_index(op.f('ix_payee_matching_patterns_id'), 'payee_matching_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_payee_matching_patterns_payee_id'), 'payee_matching_patterns', ['payee_id'], unique=False)
    op.create_index(op.f('ix_payee_matching_patterns_user_id'), 'payee_matching_patterns', ['user_id'], unique=False)
    op.drop_constraint('fk_payees_primary_pattern', 'payees', type_='foreignkey')
    op.add_column('transactions', sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_transactions_is_starred'), 'transactions', ['is_starred'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_is_starred'), table_name='transactions')
    op.drop_column('transactions', 'is_starred')
    op.create_foreign_key('fk_payees_primary_pattern', 'payees', 'payee_matching_patterns', ['primary_pattern_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_payee_matching_patterns_user_id'), table_name='payee_matching_patterns')
    op.drop_index(op.f('ix_payee_matching_patterns_payee_id'), table_name='payee_matching_patterns')
    op.drop_index(op.f('ix_payee_matching_patterns_id'), table_name='payee_matching_patterns')
    op.create_index('idx_payee_patterns_user', 'payee_matching_patterns', ['user_id'], unique=False)
    op.create_index('idx_payee_patterns_payee', 'payee_matching_patterns', ['payee_id'], unique=False)
    # ### end Alembic commands ###
