"""Add categorization_rules table

Revision ID: 75a2fd9fbc89
Revises: 879874f4adf2
Create Date: 2026-01-15 01:54:26.303601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a2fd9fbc89'
down_revision: Union[str, None] = '879874f4adf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('payee_pattern', sa.String(length=255), nullable=True),
    sa.Column('payee_match_type', sa.String(length=20), nullable=True),
    sa.Column('description_pattern', sa.String(length=255), nullable=True),
    sa.Column('description_match_type', sa.String(length=20), nullable=True),
    sa.Column('amount_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('new_payee', sa.String(length=200), nullable=True),
    sa.Column('notes_append', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('auto_created', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_user_category', 'categorization_rules', ['user_id', 'category_id'], unique=False)
    op.create_index('idx_rules_user_enabled_priority', 'categorization_rules', ['user_id', 'enabled', 'priority'], unique=False)
    op.create_index(op.f('ix_categorization_rules_id'), 'categorization_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorization_rules_id'), table_name='categorization_rules')
    op.drop_index('idx_rules_user_enabled_priority', table_name='categorization_rules')
    op.drop_index('idx_rules_user_category', table_name='categorization_rules')
    op.drop_table('categorization_rules')
    # ### end Alembic commands ###
