"""Add payee matching patterns for intelligent matching

Revision ID: c1792f7aa7ce
Revises: 5c83fac303e9
Create Date: 2026-01-18 21:11:24.543246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1792f7aa7ce'
down_revision: Union[str, None] = '5c83fac303e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create payee_matching_patterns table first
    op.create_table(
        'payee_matching_patterns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payee_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('pattern_type', sa.String(length=50), nullable=False),
        sa.Column('pattern_value', sa.String(length=500), nullable=False),
        sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False, server_default='0.80'),
        sa.Column('match_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes
    op.create_index('idx_payee_patterns_payee', 'payee_matching_patterns', ['payee_id'])
    op.create_index('idx_payee_patterns_user', 'payee_matching_patterns', ['user_id'])
    op.create_index('idx_payee_patterns_value', 'payee_matching_patterns', ['pattern_value'])
    op.create_index('idx_payee_patterns_user_payee', 'payee_matching_patterns', ['user_id', 'payee_id'])
    op.create_index(
        'idx_payee_patterns_unique',
        'payee_matching_patterns',
        ['payee_id', 'pattern_type', 'pattern_value'],
        unique=True
    )

    # Now add columns to payees table
    op.add_column('payees', sa.Column('primary_pattern_id', sa.Integer(), nullable=True))
    op.add_column('payees', sa.Column('auto_match_confidence', sa.Numeric(precision=3, scale=2), nullable=False, server_default='0.75'))

    # Add foreign key constraint for primary_pattern_id
    op.create_foreign_key(
        'fk_payees_primary_pattern',
        'payees', 'payee_matching_patterns',
        ['primary_pattern_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key and columns from payees table
    op.drop_constraint('fk_payees_primary_pattern', 'payees', type_='foreignkey')
    op.drop_column('payees', 'auto_match_confidence')
    op.drop_column('payees', 'primary_pattern_id')

    # Drop indexes
    op.drop_index('idx_payee_patterns_unique', table_name='payee_matching_patterns')
    op.drop_index('idx_payee_patterns_user_payee', table_name='payee_matching_patterns')
    op.drop_index('idx_payee_patterns_value', table_name='payee_matching_patterns')
    op.drop_index('idx_payee_patterns_user', table_name='payee_matching_patterns')
    op.drop_index('idx_payee_patterns_payee', table_name='payee_matching_patterns')

    # Drop table
    op.drop_table('payee_matching_patterns')
    # ### end Alembic commands ###
