"""add fitid column to transactions for duplicate detection

Revision ID: ca1d4344fd9d
Revises: 190752f928dd
Create Date: 2026-01-17 19:45:08.253909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1d4344fd9d'
down_revision: Union[str, None] = '190752f928dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fitid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_transactions_fitid'), 'transactions', ['fitid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_fitid'), table_name='transactions')
    op.drop_column('transactions', 'fitid')
    # ### end Alembic commands ###
